# Generated by Django 4.2.23 on 2025-08-04 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomExtraFields",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Nickname",
                    ),
                ),
                (
                    "interests",
                    models.TextField(
                        blank=True, help_text="Tell us about your hobbies and interests.", verbose_name="Interests"
                    ),
                ),
                ("wants_newsletter", models.BooleanField(default=False, verbose_name="Subscribe to newsletter")),
                (
                    "favorite_language",
                    models.CharField(
                        blank=True,
                        choices=[("python", "Python"), ("javascript", "JavaScript"), ("java", "Java"), ("go", "Go")],
                        max_length=50,
                        verbose_name="Favorite programming language",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
