# Generated by Django 4.2.23 on 2026-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_extra_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customextrafields',
            name='birthdate',
            field=models.CharField(blank=True, help_text='Use the format YYYY/MM/DD.', max_length=10, verbose_name='Date of birth'),
        ),
    ]
